# Generated by Django 5.2.17 on 2026-09-09 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('max_mark', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('midterm_max', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('assignment_max', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('summary_max', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('exam_max', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('notebook_max', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=50, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=30)),
                ('section', models.CharField(default='A', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.academicyear')),
            ],
            options={
                'ordering': ['grade', 'section'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SEMESTER_1', 'Semester 1'), ('SEMESTER_2', 'Semester 2')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear')),
            ],
            options={
                'ordering': ['academic_year_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.academicyear')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.schoolclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subject')),
            ],
        ),
    ]
